wandb_version: 1

task:
  desc: null
  value: lift
algorithm:
  desc: null
  value: cql
n_episodes:
  desc: null
  value: 3
output:
  desc: null
  value: null
_wandb:
  desc: null
  value:
    python_version: 3.8.0
    cli_version: 0.15.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1683478613.781656
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.8.0
      5: 0.15.0
      8:
      - 5
