python d3rl_cartpole_bc.py -a -e
python d3rl_cartpole_bc.py -a -e
python d3rl_cartpole_bc.py -a -e
python d3rl_cartpole_bc.py -a -e
python d3rl_cartpole_bc.py -a -e
python d3rl_cartpole_bc.py -a -e
python d3rl_cartpole_bc.py -a -e
python d3rl_cartpole_bc.py -a -e
python d3rl_cartpole_bc.py -a -e
python d3rl_cartpole_bc.py -a -e